### ISSUE TITLE
[ISSUE] MG SAIC not loaded

### ISSUE THREAD

**Issue by yvan0267** [ad-ha/mg-saic-ha#109]
### Home Assistant Version

2025.2.0

### MG/SAIC Integration Version

0.9.2

### Installation Method

HACS

### Did you check for existing issues?

- [x] Yes, I have checked for existing issues
- [ ] No, I have not checked for existing issues

### Did you enable debug logging before and are ready to post logs?

- [x] Yes, I have enabled debug logging
- [ ] No, I have not enabled debug logging

### Describe the Issue

Apparently since version 2025.2.0 MG SAIC no longer starts. Message not loaded.

### Logs

```yaml
Logger: homeassistant.setup
Source: setup.py:269
First occurred: 7:46:05 PM (1 occurrences)
Last logged: 7:46:05 PM

Setup failed for custom integration 'mg_saic': Requirements for mg_saic not found: ['saic-ismart-client-ng==0.6.0'].
```
