### ISSUE TITLE
[REQ] Sensor for voltage and current

### ISSUE THREAD

**Issue by jmerifjKriwe** [ad-ha/mg-saic-ha#119]
### Is your feature request related to a problem?

- [ ] Yes

### Please describe the problem

May I ask for two additional sensors which would be (again) quite useful if someone want to sync the data to ABRP to get more accurate calculations.

```
        double voltage = (double) chargeStatus.getBmsPackVol() * 0.25d;
        // voltage [V]: Battery pack voltage
        map.put("voltage", voltage);

        double current = chargeStatus.getBmsPackCrnt() * 0.05d - 1000.0d;
        // current [A]: Battery pack current (similar to power: output is
        // positive, input (charging) is negative.)
        map.put("current", current);
```

btw: If someone wants to know how to connect to ABRP, it's easy:

```
rest_command:
  update_abrp_mg:
    method: POST
    content_type: "charset=utf-8; application/x-www-form-urlencoded"
    url: >
      {% set tlm = {
      "utc":float(as_timestamp(states('sensor.mg_eh32_x7_last_update_time'))),
      "soc":states('sensor.mg_eh32_x7_state_of_charge'),
      "ext_temp":states('sensor.mg_eh32_x7_exterior_temperature'),
      "est_battery_range":float(states('sensor.mg_eh32_x7_electric_range')),
      "is_charging":states('sensor.mg_eh32_x7_charging_status') == "Charging",
      "is_dcfc":states('sensor.mg_eh32_x7_charging_power') > "22",
      "is_parked":states('binary_sensor.mg_eh32_x7_engine_status') == "off",
      "hvac_setpoint":state_attr('climate.mg_eh32_x7_climate','temperature'),
      "lat": state_attr('device_tracker.mg_eh32_x7_gps_location','latitude'),
      "lon": state_attr('device_tracker.mg_eh32_x7_gps_location','longitude'),
      "elevation": state_attr('device_tracker.mg_eh32_x7_gps_location','elevation'),
      "odometer": states('sensor.mg_eh32_x7_mileage'),
      "power": states('sensor.mg_eh32_x7_instant_power'),
      "speed": states('sensor.mg_eh32_x7_speed'),
      "heading": state_attr('device_tracker.mg_eh32_x7_gps_location','raw_heading'),
      "capacity": 64,
      "soe": states('sensor.mg_eh32_x7_electric_range') | float * 64 / 100,
      "car_model": "mg:mg4:22:64:luxury",
      } -%}
      https://api.iternio.com/1/tlm/send?api_key=32b2162f-9599-4647-8139-66e9f9528370&token=YOUR-OWN-TOKEN&tlm={{tlm|to_json|urlencode}}
```

you just need a token and replace YOUR-OWN-TOKEN. To get your own token just open the configuration of your car at ABRP. Choose live data and press connect a generic. It will present your token. Be carefull: every time you press the connect button again, a new token will be created.

Now just create an automation for the rest command. Something like:

```
  - id: "ABRP - Sync MG"
    alias: "ABRP Send Data MG"
    description: "Send MG4 data from Home Assistant to ABRP"
    triggers:
      - trigger: state
        entity_id: sensor.mg_eh32_x7_last_update_time
    conditions:
      - condition: state
        entity_id: input_boolean.abrp_enable_mg
        state: "on"
      - condition: template
        value_template: "{{ states('sensor.mg_eh32_x7_state_of_charge') not in ['unavailable', 'unknown', 'none'] }}"
      - condition: numeric_state
        entity_id: sensor.mg_eh32_x7_state_of_charge
        above: 0
    actions:
      - action: rest_command.update_abrp_mg
        metadata: {}
        data: {}
        response_variable: status
    mode: single
```

btw: ABRP suggest to update every 10 seconds and no longer than every 30 seconds. But currently the lowest value for "Vehicle Powered On Update Interval (in minutes)" is 1 minute. Just keep it in mind :-)

### Describe the solution you'd like

.

### Additional context

https://documenter.getpostman.com/view/7396339/SWTK5a8w

https://github.com/SAIC-iSmart-API/saic-java-client/blob/76e4ca8504155fc9ae75e3c847495115d87fd632/saic-java-client/src/main/java/net/heberling/ismart/abrp/ABRP.java#L46
https://github.com/SAIC-iSmart-API/saic-java-client/blob/76e4ca8504155fc9ae75e3c847495115d87fd632/saic-java-client/src/main/java/net/heberling/ismart/abrp/ABRP.java#L50
