### ISSUE TITLE
[ISSUE] India "Failed to authenticate, please check your credentials"

### ISSUE THREAD

**Issue by ceaswaran** [ad-ha/mg-saic-ha#129]
### Home Assistant Version

2025.2.5

### MG/SAIC Integration Version

0.9.4

### Installation Method

HACS

### Did you check for existing issues?

- [x] Yes, I have checked for existing issues
- [ ] No, I have not checked for existing issues

### Did you enable debug logging before and are ready to post logs?

- [x] Yes, I have enabled debug logging
- [ ] No, I have not enabled debug logging

### Describe the Issue

After clicking the "+ Add Integration" button and searching for "MG SAIC", none of the authentication methods work. I tried both Mobile and Email options.

I also selected every available country, but for all combinations, I receive the following error message:
"Failed to authenticate, please check your credentials."

However, the same mobile credentials work fine in the Android app.

I am from India (+91), and in the Android app, we enter the username as a 10-digit mobile number without the country code.

Kindly assist in resolving this issue.

<img width="333" alt="Image" src="https://github.com/user-attachments/assets/12860535-8a52-43ea-84c4-90429d20ec98" />

### Logs

```yaml
This error originated from a custom integration.

Logger: custom_components.mg_saic
Source: custom_components/mg_saic/config_flow.py:101
integration: mg_saic (documentation, issues)
First occurred: 10:13:36 PM (1 occurrences)
Last logged: 10:13:36 PM

Failed to authenticate or fetch vehicle data: return code: 1000036, message: The account is not registered.

This error originated from a custom integration.

Logger: saic_ismart_client_ng.api.base
Source: custom_components/mg_saic/config_flow.py:214
integration: mg_saic (documentation, issues)
First occurred: 10:13:36 PM (1 occurrences)
Last logged: 10:13:36 PM

API call return code is not acceptable: 1000036: {"code":1000036,"message":"The account is not registered."}. Headers: Headers({'date': 'Tue, 04 Mar 2025 16:43:36 GMT', 'content-type': 'application/x-www-form-urlencoded', 'connection': 'keep-alive', 'x-content-type-options': 'nosniff', 'x-xss-protection': '1; mode=block', 'cache-control': 'no-cache, no-store, max-age=0, must-revalidate', 'pragma': 'no-cache', 'expires': '0', 'x-frame-options': 'DENY', 'app-content-encrypted': '1', 'original-content-type': 'application/x-www-form-urlencoded', 'app-send-date': '1741106616130', 'app-verification-string': '890a92c32ce11379786a9b0abd35bb6b4109cacb8b52083cf35209b9c3695593', 'content-length': '59'})
```
