### ISSUE TITLE
[ISSUE] Action to heat seats

### ISSUE THREAD

**Issue by Johndowne** [ad-ha/mg-saic-ha#134]
### Home Assistant Version

2025.3.3

### MG/SAIC Integration Version

0.9.4

### Installation Method

HACS

### Did you check for existing issues?

- [x] Yes, I have checked for existing issues
- [ ] No, I have not checked for existing issues

### Did you enable debug logging before and are ready to post logs?

- [x] Yes, I have enabled debug logging
- [ ] No, I have not enabled debug logging

### Describe the Issue

Trying out Run of script

![Image](https://github.com/user-attachments/assets/2e29d418-8255-4f9e-811a-7c4ea30c2385)

to heat seats gives this message on black background….
“Failed to perform the action script/mg_heat_seats. extra keys not allowed @ data['left_level']”

I’ve set heat level for both seats in Script

### Logs

```yaml
Logger: homeassistant.components.script.mg_heat_seats
Source: helpers/script.py:2058
integration: Scripts (documentation, issues)
First occurred: 22:55:41 (8 occurrences)
Last logged: 23:13:28

MG heat seats: Error executing script. Invalid data for call_service at pos 1: extra keys not allowed @ data['left_level']
MG heat seats: Error executing script. Invalid data for call_service at pos 1: required key not provided @ data['seat']
MG heat seats: Already running
```
