### ISSUE TITLE
[ISSUE] Integration fails

### ISSUE THREAD

**Issue by roydestroy** [ad-ha/mg-saic-ha#153]
### Home Assistant Version

2025.5.3

### MG/SAIC Integration Version

0.9.5

### Installation Method

HACS

### Did you check for existing issues?

- [x] Yes, I have checked for existing issues
- [ ] No, I have not checked for existing issues

### Did you enable debug logging before and are ready to post logs?

- [x] Yes, I have enabled debug logging
- [ ] No, I have not enabled debug logging

### Describe the Issue

Suddenly the integration failed to start and gave me this error.
Failed to authenticate or fetch vehicle data: return code: 403, message: {"code":403,"message":"Illegal AppSendDate!"}
I tried many things one of them was reinstalling the integration and now I am not able to authenticate at all.

### Logs

```yaml
This error originated from a custom integration.

Logger: custom_components.mg_saic
Source: custom_components/mg_saic/config_flow.py:101
integration: MG SAIC Integration (documentation, issues)
First occurred: 09:35:44 (2 occurrences)
Last logged: 09:36:11

Failed to authenticate or fetch vehicle data: return code: 403, message: {"code":403,"message":"Illegal AppSendDate!"}
```
