### ISSUE TITLE
[ISSUE] I can no longer connect to my accout

### ISSUE THREAD

**Issue by topcat36** [ad-ha/mg-saic-ha#154]
![Image](https://github.com/user-attachments/assets/b6867933-bebd-4d06-9bb5-d0092bcf0f8d)

### Home Assistant Version

2025.5.3

### MG/SAIC Integration Version

0.9.5

### Installation Method

HACS

### Did you check for existing issues?

- [x] Yes, I have checked for existing issues
- [x] No, I have not checked for existing issues

### Did you enable debug logging before and are ready to post logs?

- [x] Yes, I have enabled debug logging
- [x] No, I have not enabled debug logging

### Describe the Issue

The addon stopped working yesterday after I restarted HA because of an update of some other addons. This happened before but after I unlock the car and sometimes log-in using the MG App, the Saic addon started working again. Unfortunately this time did not. I waited one one day but still no success. 
Today I removed my accout from the addon and tried reconfiguring it but now I get a "Failed to authenticate message". The MG app works perfect, I logged off and on a few times, checked the user/pass and all are correct but still, the addon refuses to connect. What is happening ?

### Logs

```yaml
This error originated from a custom integration.

Logger: saic_ismart_client_ng.api.base
Source: custom_components/mg_saic/config_flow.py:214
integration: MG SAIC Integration (documentation, issues)
First occurred: 9:07:37 AM (5 occurrences)
Last logged: 9:30:28 AM

API call return code is not acceptable: 6: {"code":6,"message":"The service is not available,please try again later."}. Headers: Headers({'date': 'Sun, 01 Jun 2025 06:07:37 GMT', 'content-type': 'application/x-www-form-urlencoded', 'connection': 'keep-alive', 'x-content-type-options': 'nosniff', 'x-xss-protection': '1; mode=block', 'cache-control': 'no-cache, no-store, max-age=0, must-revalidate', 'pragma': 'no-cache', 'expires': '0', 'x-frame-options': 'DENY', 'app-content-encrypted': '1', 'original-content-type': 'application/x-www-form-urlencoded', 'app-send-date': '1748758057439', 'app-verification-string': '074c462b103a36ee7827b916699419f5c49d382bf92dc898364fe34948eb1d35', 'content-length': '75'})
API call return code is not acceptable: 6: {"code":6,"message":"The service is not available,please try again later."}. Headers: Headers({'date': 'Sun, 01 Jun 2025 06:08:17 GMT', 'content-type': 'application/x-www-form-urlencoded', 'connection': 'keep-alive', 'x-content-type-options': 'nosniff', 'x-xss-protection': '1; mode=block', 'cache-control': 'no-cache, no-store, max-age=0, must-revalidate', 'pragma': 'no-cache', 'expires': '0', 'x-frame-options': 'DENY', 'app-content-encrypted': '1', 'original-content-type': 'application/x-www-form-urlencoded', 'app-send-date': '1748758097411', 'app-verification-string': 'f4e5551c18d943108e57b62104701e3c1d3b5e1f1230f706d592fc3ed29f4211', 'content-length': '75'})
API call return code is not acceptable: 15018: {"code":15018,"message":"Incorrect password. You may have another 4 attempts of the day, please try again."}. Headers: Headers({'date': 'Sun, 01 Jun 2025 06:11:18 GMT', 'content-type': 'application/x-www-form-urlencoded', 'connection': 'keep-alive', 'x-content-type-options': 'nosniff', 'x-xss-protection': '1; mode=block', 'cache-control': 'no-cache, no-store, max-age=0, must-revalidate', 'pragma': 'no-cache', 'expires': '0', 'x-frame-options': 'DENY', 'app-content-encrypted': '1', 'original-content-type': 'application/x-www-form-urlencoded', 'app-send-date': '1748758278564', 'app-verification-string': '1e26c9797fb4e7c42d45b5260ee02dc0f6287601f7b9b0f81e5042f073dc6c09', 'content-length': '108'})
API call return code is not acceptable: 1000036: {"code":1000036,"message":"The account is not registered."}. Headers: Headers({'date': 'Sun, 01 Jun 2025 06:12:32 GMT', 'content-type': 'application/x-www-form-urlencoded', 'connection': 'keep-alive', 'x-content-type-options': 'nosniff', 'x-xss-protection': '1; mode=block', 'cache-control': 'no-cache, no-store, max-age=0, must-revalidate', 'pragma': 'no-cache', 'expires': '0', 'x-frame-options': 'DENY', 'app-content-encrypted': '1', 'original-content-type': 'application/x-www-form-urlencoded', 'app-send-date': '1748758352440', 'app-verification-string': '24fc88a90d10d7649026fc7afb4fd3bc213443be10549bfef01a003c710ca09a', 'content-length': '59'})
API call return code is not acceptable: 6: {"code":6,"message":"The service is not available,please try again later."}. Headers: Headers({'date': 'Sun, 01 Jun 2025 06:30:28 GMT', 'content-type': 'application/x-www-form-urlencoded', 'connection': 'keep-alive', 'x-content-type-options': 'nosniff', 'x-xss-protection': '1; mode=block', 'cache-control': 'no-cache, no-store, max-age=0, must-revalidate', 'pragma': 'no-cache', 'expires': '0', 'x-frame-options': 'DENY', 'app-content-encrypted': '1', 'original-content-type': 'application/x-www-form-urlencoded', 'app-send-date': '1748759428087', 'app-verification-string': '585981b4cb0bfcfb49023dd7857f6aa8b140a067d7a7d5db0038b314217a96fc', 'content-length': '75'})
```
